name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write  # 需要写权限以便自动commit & push
  pages: write
  id-token: write

jobs:
  build_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install cheerio
      - run: node .github/scripts/generate-menu.js
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: auto-generate indexes"
            git push
          fi

  deploy:
    needs: build_and_commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      # 可能还要npm build之类的...

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # 这时仓库已含最新index.html / menu.js
      - name: Deploy
        uses: actions/deploy-pages@v2
