name: Generate Menu
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1) 拉取仓库
      - uses: actions/checkout@v2

      # 2) 设置 Node
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # 3) 安装依赖
      - name: Install dependencies
        run: |
          npm install cheerio

      # 4) 执行脚本
      - name: Generate indexes
        run: |
          node .github/scripts/generate-menu.js
      
      # 5) 提交并推送
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: auto-generate indexes"
            git push
          else
            echo "No changes to commit."
          fi